import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertTriangle, BedDouble, Building2, ClipboardList, FileCheck2, IndianRupee, LogOut, MessageSquareWarning, Users } from "lucide-react";
import { createSupabaseServer } from "@/lib/supabase/server";
const staffRoles=new Set(["super_admin","admin","manager","staff","accountant"]);
export default async function AdminPage(){
 const supabase=await createSupabaseServer();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:roles}=await supabase.from("user_roles").select("role").eq("user_id",user.id);if(!roles?.some(r=>staffRoles.has(r.role)))redirect("/member");
 const [members,apps,rooms,beds,complaints,pending]=await Promise.all([
  supabase.from("members").select("id",{count:"exact",head:true}),
  supabase.from("applications").select("id",{count:"exact",head:true}).in("status",["submitted","under_review","documents_required"]),
  supabase.from("rooms").select("id",{count:"exact",head:true}),
  supabase.from("beds").select("id",{count:"exact",head:true}).eq("status","available"),
  supabase.from("complaints").select("id",{count:"exact",head:true}).in("status",["submitted","acknowledged","assigned","in_progress","reopened"]),
  supabase.from("applications").select("id,application_code,status,created_at").in("status",["submitted","under_review","documents_required"]).order("created_at",{ascending:false}).limit(6)
 ]);
 const metrics=[["Members",members.count||0,Users],["Rooms",rooms.count||0,Building2],["Available beds",beds.count||0,BedDouble],["Applications",apps.count||0,ClipboardList],["Open complaints",complaints.count||0,MessageSquareWarning]] as const;
 return <main className="dashboard-page"><header className="dash-top"><Link href="/" className="brand"><span className="brand-mark"><Building2 size={18}/></span><span><b>JAY BOYS</b><small>OPERATIONS CONSOLE</small></span></Link><Link href="/api/auth/signout" className="icon-button"><LogOut size={16}/></Link></header><div className="dash-wrap"><div className="dash-heading"><span className="eyebrow"><Building2 size={14}/> LIVE DATABASE VIEW</span><h1>Operations command center.</h1><p>These metrics are queried from Supabase. Zero means there is no matching database record, not simulated data.</p></div><section className="data-grid admin-metrics">{metrics.map(([label,value,Icon])=><article className="data-card" key={label}><Icon/><span>{label.toUpperCase()}</span><b>{value}</b><small>Current database count</small></article>)}</section><section className="dash-columns"><div className="panel"><div className="panel-head"><div><span>WORK QUEUE</span><h2>Applications to review</h2></div><ClipboardList/></div>{pending.data?.length?<div className="table-list">{pending.data.map(a=><div key={a.id}><span><b>{a.application_code}</b><small>{a.status.replaceAll("_"," ")}</small></span><span>{new Date(a.created_at).toLocaleDateString("en-IN")}</span></div>)}</div>:<div className="empty-state">No applications are waiting for staff review.</div>}</div><div className="panel"><div className="panel-head"><div><span>OPERATIONS</span><h2>Quick access</h2></div><FileCheck2/></div><div className="quick-links vertical"><Link href="/admin/applications"><ClipboardList/> Applications</Link><Link href="/admin/members"><Users/> Members</Link><Link href="/admin/rooms"><BedDouble/> Rooms</Link><Link href="/admin/beds"><BedDouble/> Beds</Link><Link href="/admin/tenancies"><Building2/> Tenancies</Link><Link href="/admin/billing"><IndianRupee/> Invoices</Link><Link href="/admin/payments"><IndianRupee/> Payments</Link><Link href="/admin/complaints"><AlertTriangle/> Complaints</Link><Link href="/admin/announcements"><MessageSquareWarning/> Announcements</Link><Link href="/admin/documents"><FileCheck2/> Documents</Link><Link href="/admin/pricing"><IndianRupee/> Pricing</Link><Link href="/admin/notifications"><MessageSquareWarning/> Notifications</Link><Link href="/admin/hostels"><Building2/> Hostels</Link><Link href="/admin/buildings"><Building2/> Buildings</Link><Link href="/admin/floors"><Building2/> Floors</Link><Link href="/admin/document_types"><FileCheck2/> Document types</Link><Link href="/admin/feature_flags"><Building2/> Feature flags</Link><Link href="/admin/settings"><Building2/> Settings</Link><Link href="/admin/roles"><Users/> Roles</Link><Link href="/admin/audit"><FileCheck2/> Audit log</Link></div></div></section></div></main>
}