"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, FileText, ShieldCheck, Sparkles } from "lucide-react";
const fields=[["full_name","Full name"],["father_name","Father's name"],["mother_name","Mother's name"],["phone","Mobile number"],["email","Email"],["institution","Institution"],["course","Course"],["academic_year","Academic year"],["city","City"],["state","State"],["postal_code","PIN code"],["address","Permanent address"]];
export default function ApplyPage(){
 const [form,setForm]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [done,setDone]=useState("");const [error,setError]=useState("");
 function update(k:string,v:string){setForm(x=>({...x,[k]:v}))}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Unable to submit application.");setDone(data.application_code)}catch(err){setError(err instanceof Error?err.message:"Unable to submit application.")}finally{setBusy(false)}}
 return <main className="auth-page"><div className="dash-wrap" style={{maxWidth:980}}><Link href="/" className="back-link"><ArrowLeft size={15}/> Back to hostel</Link><div className="setup-card" style={{maxWidth:"none",marginTop:24}}><span className="eyebrow"><Sparkles size={14}/> DIGITAL ADMISSION</span><h1 style={{fontSize:"clamp(42px,6vw,68px)",letterSpacing:"-.055em",margin:"15px 0 8px"}}>Make your move.</h1><p>Submit a real application record. Staff can review it from the operations console after Supabase is configured.</p></div>{done?<div className="setup-card" style={{maxWidth:"none"}}><CheckCircle2 size={36} color="#63e6e2"/><h2>Application received</h2><p>Your application code is <b style={{color:"#fff"}}>{done}</b>. Keep it for your records.</p><Link href="/" className="button primary">Back to site</Link></div>:<form onSubmit={submit} className="panel" style={{marginTop:12}}><div className="panel-head"><div><span>APPLICATION</span><h2>Resident details</h2></div><FileText/></div><div className="data-grid" style={{gridTemplateColumns:"repeat(2,1fr)",marginTop:22}}>{fields.map(([key,label])=><label key={key} style={{display:"grid",gap:7,fontSize:11,color:"#aab4c2"}}>{label}<input value={form[key]||""} onChange={e=>update(key,e.target.value)} required={["full_name","phone","email"].includes(key)} style={{width:"100%",padding:"13px 14px",background:"#ffffff03",border:"1px solid rgba(255,255,255,.09)",borderRadius:12,color:"#fff",outline:"none"}}/></label>)}</div>{error&&<div className="form-error" style={{marginTop:16}}>{error}</div>}<div style={{marginTop:22,display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><span className="trust-row"><ShieldCheck size={14}/> Sensitive operations remain server-side.</span><button className="button primary" disabled={busy}>{busy?"Submitting…":"Submit application"} <ArrowRight size={16}/></button></div></form>}</div></main>
}