"use client";
import {motion} from "framer-motion";
import {ArrowRight,BedDouble,Building2,CheckCircle2,FileText,IndianRupee,ShieldCheck,Sparkles,UsersRound} from "lucide-react";
import Link from "next/link";
const stats=[["24/7","Resident support"],["Live","Bed availability"],["100%","Digital records"],["Secure","Supabase-backed data"]];
export default function HomePage(){return <main className="min-h-screen">
<nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6 lg:px-8">
<div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-white/10 ring-1 ring-white/10"><Building2 className="size-5 text-emerald-300"/></div><div><div className="font-semibold">Jay Boys Hostel</div><div className="text-xs text-slate-400">Vinoba Nagar · Indore</div></div></div>
<div className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><a href="#rooms">Rooms</a><a href="#facilities">Facilities</a><a href="#process">Admission</a><a href="#contact">Contact</a></div>
<Link href="/login" className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm font-medium hover:bg-white/10">Member Login</Link></nav>
<section className="relative overflow-hidden px-4 pb-20 pt-10 sm:px-6 lg:px-8 lg:pb-28 lg:pt-20"><div className="absolute inset-0 -z-10 grid-bg opacity-40"/><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.1fr_.9fr]">
<div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1.5 text-xs text-emerald-200"><Sparkles className="size-3.5"/> Digital hostel experience</div>
<h1 className="max-w-4xl text-5xl font-semibold tracking-tight sm:text-6xl lg:text-7xl">Stay organized. <span className="text-emerald-300">Live comfortably.</span></h1>
<p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">A modern resident experience for admissions, room allocation, fees, documents, announcements and complaints — powered by one connected hostel command center.</p>
<div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/apply" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-300 px-5 py-3 font-semibold text-slate-950">Apply for Admission <ArrowRight className="size-4"/></Link><a href="#rooms" className="inline-flex items-center justify-center rounded-2xl border border-white/10 bg-white/5 px-5 py-3 font-semibold hover:bg-white/10">Explore Hostel</a></div>
<div className="mt-10 grid max-w-2xl grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(([value,label])=><div key={label} className="glass rounded-2xl p-4"><div className="text-xl font-semibold">{value}</div><div className="mt-1 text-xs text-slate-400">{label}</div></div>)}</div></div>
<motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="relative"><div className="glass relative rounded-[2rem] p-5 sm:p-7"><div className="flex items-center justify-between"><div><div className="text-sm text-slate-400">Hostel command center</div><div className="mt-1 text-2xl font-semibold">Today at a glance</div></div><div className="rounded-xl bg-emerald-300/10 p-2.5"><ShieldCheck className="size-5 text-emerald-300"/></div></div>
<div className="mt-7 grid grid-cols-2 gap-3">{[[UsersRound,"Active residents","94"],[BedDouble,"Available beds","18"],[IndianRupee,"Collections today","₹24,500"],[FileText,"Open complaints","4"]].map(([Icon,label,value])=>{const C=Icon as typeof UsersRound;return <div key={label as string} className="rounded-2xl border border-white/8 bg-black/10 p-4"><C className="size-5 text-sky-300"/><div className="mt-5 text-2xl font-semibold">{value as string}</div><div className="mt-1 text-xs text-slate-400">{label as string}</div></div>})}</div>
<div className="mt-4 rounded-2xl border border-white/8 bg-black/10 p-4"><div className="flex items-center justify-between text-xs text-slate-400"><span>Occupancy</span><span>78.3%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full w-[78.3%] rounded-full bg-emerald-300"/></div></div></div>
<motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.3}} className="absolute -bottom-5 -left-4 rounded-2xl border border-emerald-300/15 bg-emerald-300/10 px-4 py-3 text-xs text-emerald-100 shadow-2xl"><CheckCircle2 className="mr-2 inline size-4"/> Live room & bed allocation</motion.div></motion.div></div></section>
<section id="rooms" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><div className="text-sm font-medium text-emerald-300">Accommodation</div><h2 className="mt-2 text-3xl font-semibold sm:text-4xl">Rooms managed like an operating system.</h2><p className="mt-4 text-slate-400">Room types, rates, occupancy and individual beds remain configurable from the admin command center.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[["2 Sharing","Comfort-focused twin room","From ₹7,000 / month"],["3 Sharing","Balanced shared living","From ₹6,000 / month"],["4 Sharing","Efficient student accommodation","From ₹5,000 / month"]].map(([title,desc,price])=><div key={title} className="glass rounded-3xl p-6"><div className="text-xl font-semibold">{title}</div><p className="mt-2 text-sm text-slate-400">{desc}</p><div className="mt-7 text-sm font-medium text-emerald-300">{price}</div></div>)}</div></section>
<section id="facilities" className="border-y border-white/5 bg-white/[.02]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Wi-Fi","Stay connected"],["Security","Resident-first safety"],["Study","Focused common areas"],["Support","Fast complaint handling"]].map(([title,desc])=><div key={title} className="rounded-2xl border border-white/6 bg-black/10 p-5"><div className="text-base font-semibold">{title}</div><div className="mt-2 text-sm text-slate-400">{desc}</div></div>)}</div></div></section>
<section id="process" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><div className="text-sm font-medium text-sky-300">Admission flow</div><h2 className="mt-2 text-3xl font-semibold sm:text-4xl">From application to room key without the paperwork maze.</h2></div><div className="mt-10 grid gap-4 lg:grid-cols-5">{["Apply","Upload documents","Admin verification","Room + bed allocation","Check-in"].map((step,i)=><div key={step} className="glass rounded-3xl p-5"><div className="text-sm text-slate-500">0{i+1}</div><div className="mt-5 font-semibold">{step}</div><p className="mt-2 text-sm text-slate-400">Tracked with status history and auditability.</p></div>)}</div></section>
<footer id="contact" className="border-t border-white/5 px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-sm text-slate-400 md:flex-row"><div><div className="font-semibold text-white">Jay Boys Hostel</div><div className="mt-1">Vinoba Nagar, Indore, Madhya Pradesh</div></div><div>Owner-verifiable contact, pricing and property information should be managed from Admin Settings.</div></div></footer></main>}