"use client";
import Link from "next/link";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { ArrowRight, BedDouble, Building2, CalendarDays, Check, ChevronRight, FileText, IndianRupee, LifeBuoy, ShieldCheck, Sparkles, Users, Wifi } from "lucide-react";

const features=[
 ["Admissions","Apply, upload documents and track verification.",FileText],
 ["Rooms & beds","See the accommodation model without fake availability claims.",BedDouble],
 ["Resident care","Keep notices, complaints, documents and billing together.",LifeBuoy],
 ["Secure access","Role-aware access is designed around Supabase RLS.",ShieldCheck]
] as const;
const principles=["Mobile-first resident experience","Admin workflows built around real records","Server-side handling for sensitive operations","Supabase PostgreSQL as the source of truth"];

export default function HomePage(){
 const [content,setContent]=useState<Record<string,any>>({});
 useEffect(()=>{fetch("/api/public/site-content",{cache:"no-store"}).then(r=>r.json()).then(x=>{const map:Record<string,any>={};for(const item of x.data||[])map[item.key]=item;setContent(map)}).catch(()=>{});},[]);
 const hero=content.hero||{}; const experience=content.experience||{}; const facilities=content.facilities||{}; const admission=content.admission||{}; const cta=content.cta||{};
 return <main className="site-shell"><div className="noise"/>
  <nav className="topbar"><Link href="/" className="brand"><span className="brand-mark"><Building2 size={19}/></span><span><b>JAY BOYS</b><small>HOSTEL · INDORE</small></span></Link><div className="nav-links"><a href="#experience">Experience</a><a href="#facilities">Facilities</a><a href="#process">Admission</a></div><Link href="/login" className="nav-cta">Resident / Staff <ChevronRight size={16}/></Link></nav>
  <section className="hero"><div className="hero-copy"><motion.div initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} className="eyebrow"><Sparkles size={14}/> DIGITAL HOSTEL PLATFORM</motion.div><motion.h1 initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{delay:.08}}>{hero.title||"Stay simple."}<br/><em>{hero.subtitle||"Live connected."}</em></motion.h1><p className="hero-copy">{hero.body||"Jay Boys Hostel brings admissions, accommodation, resident records, billing, documents and support into one focused experience for Vinoba Nagar, Indore."}</p><div className="hero-actions"><Link href="/apply" className="button primary">{hero.cta_label||"Start admission"} <ArrowRight size={17}/></Link><Link href="/login" className="button ghost">Open resident portal</Link></div><div className="trust-row"><span><Check size={14}/> Responsive by design</span><span><Check size={14}/> Supabase-ready</span><span><Check size={14}/> Role-aware</span></div></div>
  <div className="hero-stage"><div className="stage-glow"/><div className="building"><div className="building-top"><span>JAY BOYS</span><small>VINOBA NAGAR · INDORE</small></div><div className="building-grid">{Array.from({length:18}).map((_,i)=><span key={i} className={i%5===0?"window lit":"window"}/>)}</div><div className="building-base"><span>RESIDENT LIFE</span><span>2026</span></div></div><motion.div animate={{y:[0,-10,0]}} transition={{duration:5,repeat:Infinity}} className="float-card float-one"><BedDouble size={18}/><span><b>Rooms</b><small>Structured allocation</small></span></motion.div><motion.div animate={{y:[0,8,0]}} transition={{duration:4.2,repeat:Infinity}} className="float-card float-two"><ShieldCheck size={18}/><span><b>Protected</b><small>Role-based access</small></span></motion.div></div></section>
  <section id="experience" className="section"><div className="section-intro"><span>01 / PLATFORM</span><h2>{experience.title||"One system for the stay."}</h2><p>{experience.body||"Designed as a product, not a collection of disconnected screens."}</p></div><div className="feature-grid">{features.map(([title,desc,Icon],i)=><motion.article whileHover={{y:-6}} key={title} className="feature-card"><div className="feature-icon"><Icon size={21}/></div><span className="card-index">0{i+1}</span><h3>{title}</h3><p>{desc}</p><ArrowRight className="card-arrow" size={18}/></motion.article>)}</div></section>
  <section id="facilities" className="section split-section"><div><div className="section-intro"><span>02 / DAILY LIFE</span><h2>{facilities.title||"Built around what residents actually need."}</h2></div><div className="principles">{principles.map((item,i)=><div key={item}><span>0{i+1}</span><p>{item}</p></div>)}</div></div><div className="dashboard-preview"><div className="preview-head"><span>Resident workspace</span><span className="live"><i/> READY</span></div><div className="preview-card big"><div><small>MY STAY</small><b>Room & bed details</b></div><BedDouble/></div><div className="preview-row"><div className="preview-card"><IndianRupee/><small>Billing</small><b>Invoices</b></div><div className="preview-card"><CalendarDays/><small>Timeline</small><b>Stay dates</b></div></div><div className="preview-note"><Wifi size={16}/><span><b>Connected experience</b><small>Announcements, documents and support in one place.</small></span></div></div></section>
  <section id="process" className="section"><div className="section-intro"><span>03 / ADMISSION</span><h2>{admission.title||"From application to check-in."}</h2></div><div className="process-grid">{[["01","Apply","Enter resident and guardian details."],["02","Verify","Submit documents for hostel review."],["03","Allocate","Staff assign the room and bed."],["04","Move in","Billing and support continue digitally."]].map(([n,t,d])=><div key={n} className="process-card"><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></section>
  <section className="final-cta"><div><span>JAY BOYS HOSTEL · VINOBA NAGAR</span><h2>{cta.title||"A better hostel workflow starts here."}</h2></div><Link href="/apply" className="button primary">Apply now <ArrowRight size={17}/></Link></section>
  <footer className="footer"><span>© Jay Boys Hostel</span><span>Vinoba Nagar · Indore · Madhya Pradesh</span><span>Admissions · Resident Portal · Operations</span></footer>
 </main>
}
